import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Generated by `flutterfire configure` — uncomment once you run it:
// import 'firebase_options.dart';

import 'core/theme/app_theme.dart';
import 'providers/auth_provider.dart';
import 'providers/expense_provider.dart';
import 'providers/budget_provider.dart';
import 'providers/insight_provider.dart';
import 'router/app_router.dart';
import 'services/notification_service.dart';

// ── Theme notifier ────────────────────────────────────────────────────────────
class ThemeNotifier extends ChangeNotifier {
  bool _isDark = false;
  bool get isDark => _isDark;

  ThemeNotifier() {
    _load();
  }

  Future<void> _load() async {
    final prefs = await SharedPreferences.getInstance();
    _isDark = prefs.getBool('dark_mode') ?? false;
    notifyListeners();
  }

  Future<void> toggle(bool value) async {
    _isDark = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('dark_mode', value);
  }
}

// ── Entry point ───────────────────────────────────────────────────────────────
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase.
  // If you have run `flutterfire configure`, swap in:
  //   options: DefaultFirebaseOptions.currentPlatform
  await Firebase.initializeApp();

  // Init local notifications (non-fatal if it fails on desktop/web).
  try {
    await NotificationService.instance.initialize();
    await NotificationService.instance.scheduleDailySavingsReminder();
  } catch (_) {
    // Notifications are optional — don't crash if they fail.
  }

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  runApp(const ExpenseTrackerApp());
}

// ── Root widget ───────────────────────────────────────────────────────────────
class ExpenseTrackerApp extends StatelessWidget {
  const ExpenseTrackerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeNotifier()),
        ChangeNotifierProvider(create: (_) => AppAuthProvider()),
        ChangeNotifierProvider(create: (_) => ExpenseProvider()),
        ChangeNotifierProvider(create: (_) => BudgetProvider()),
        ChangeNotifierProvider(create: (_) => InsightProvider()),
      ],
      child: Consumer<ThemeNotifier>(
        builder: (_, themeNotifier, child) => MaterialApp(
          title: 'PanamFlow',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode:
              themeNotifier.isDark ? ThemeMode.dark : ThemeMode.light,
          initialRoute: AppRouter.splash,
          onGenerateRoute: AppRouter.generateRoute,
        ),
      ),
    );
  }
}
